name: Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and push staging docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into Docker Hub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image
        run: make ci-build-staging
      
      - name: Notify to slack
        run: curl --fail -X POST --data-urlencode "payload={'text': '[docker] pluto:staging built'}" "${{ secrets.SLACK_WEBHOOK }}"
        
      - name: Deploy to staging
        run: curl "${{ secrets.STAGING_DEPLOY_WEBHOOK }}"
