name: docker_publish_production

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build and push production docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into Docker Hub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image
        run: export VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') && make ci-build-production
